import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hindsol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Fixed horizontal div */}
        <div className="fixedSidebar">
          {/* Links to social media platforms */}
          <a href="https://www.facebook.com/hindsolsoftware/" target="_blank" rel="noopener noreferrer">
            <img src="/assets/facebook.png" />
          </a>
          <a href="https://www.instagram.com/hindsolsoftware/" target="_blank" rel="noopener noreferrer">
          <img src="/assets/instagram.png" />
          </a>
          <a href="https://www.whatsapp.com/hindsol" target="_blank" rel="noopener noreferrer">
          <img src="/assets/whatsapp.png" />
          </a>
          {/* Add more social media links/icons as needed */}
        </div>
        {/* Main content */}
        {children}
      </body>
    </html>
  );
}
